version: "3.4"

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=${IdentityServerUrl}
    ports:
      - "80"

  workoutwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbConnectionString=${MongoDbConnectionString}
      - IdentityServerUrl=${IdentityServerUrl}
    ports:
      - "80"

  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UrlIssuerName=${IdentityServerUrl}
    ports:
      - "80"
